DROP DATABASE IF EXISTS T4_BBDDjuego;
CREATE DATABASE T4_BBDDjuego;

USE T4_BBDDjuego;

CREATE TABLE PLAYER (
	ID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
 	GAMES_WON INT,
	BEST_GAME INT,
	GAMES_PLAYED INT,
	PRIMARY KEY (ID)
)ENGINE = InnoDB;

CREATE TABLE GAME (
	ID INT NOT NULL,
	DATE INT NOT NULL,
	PRIMARY KEY (ID)	
)ENGINE = InnoDB;

CREATE TABLE PARTICIPANTS (
	ID_P INT NOT NULL,
	ID_G INT NOT NULL,
	FOREIGN KEY (ID_P) REFERENCES PLAYER(ID),
	FOREIGN KEY (ID_G) REFERENCES GAME(ID)
)ENGINE = InnoDB;
	

INSERT INTO PLAYER (ID,NAME,PASSWORD,GAMES_WON,BEST_GAME,GAMES_PLAYED) VALUES ('1','Lin','123','0','0','0');
INSERT INTO PLAYER (ID,NAME,PASSWORD,GAMES_WON,BEST_GAME,GAMES_PLAYED) VALUES ('2','Pau','321','0','0','0');
INSERT INTO PLAYER (ID,NAME,PASSWORD,GAMES_WON,BEST_GAME,GAMES_PLAYED) VALUES ('3','Guille','213','0','0','0');
